### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'fuse' on MacOs Big Sur

### ISSUE THREAD

**Issue by zishanjms** [centic9/JGitFS#26]
Getting below error while running the JGitFS:
`zishanalisaiyed@Apples-MacBook-Pro JGitFS % build/install/JGitFS/bin/JGitFS /Users/zishanalisaiyed/Downloads/cms/prod/cms_local /Users/zishanalisaiyed/cms-git-data/
Mounting git repository at /Users/zishanalisaiyed/Downloads/cms/prod/cms_local/ at mountpoint /Users/zishanalisaiyed/cms-git-data
Using git repo at /Users/zishanalisaiyed/Downloads/cms/prod/cms_local/.git
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'fuse': JNA native support (darwin/libfuse.jnilib) not found in resource path (/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/JGitFS.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/fuse-jna-1.0.3.2.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-dost-1.0.0.33.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-io-2.11.0.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-text-1.9.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-lang3-3.12.0.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/jna-3.5.2.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/org.eclipse.jgit-5.13.0.202109080827-r.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/guava-31.0.1-jre.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/jline-2.14.6.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/slf4j-simple-1.7.32.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/httpasyncclient-4.1.4.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/httpclient-4.5.13.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-exec-1.3.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/log4j-api-2.14.1.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/JavaEWAH-1.1.12.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/slf4j-api-1.7.32.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/failureaccess-1.0.1.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/jsr305-3.0.2.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/checker-qual-3.12.0.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/error_prone_annotations-2.7.1.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/j2objc-annotations-1.3.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/httpcore-nio-4.4.10.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/httpcore-4.4.13.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-logging-1.2.jar:/Users/zishanalisaiyed/br/JGitFS/build/install/JGitFS/lib/commons-codec-1.11.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:220)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:322)
	at com.sun.jna.Library$Handler.<init>(Library.java:142)
	at com.sun.jna.Native.loadLibrary(Native.java:387)
	at com.sun.jna.Native.loadLibrary(Native.java:366)
	at net.fusejna.Platform.init(Platform.java:77)
	at net.fusejna.Platform.fuse(Platform.java:26)
	at net.fusejna.FuseJna.init(FuseJna.java:133)
	at net.fusejna.FuseJna.mount(FuseJna.java:193)
	at net.fusejna.FuseFilesystem.mount(FuseFilesystem.java:571)
	at org.dstadler.jgitfs.JGitFS.mount(JGitFS.java:117)
	at org.dstadler.jgitfs.JGitFS.main(JGitFS.java:45)
zishanalisaiyed@Apples-MacBook-Pro JGitFS % `

I have set the Java_Home before running the application. 
`echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home`

**Comment by centic9** [comment]
It seems you are missing support for user-space filesystem which is usually provided via the "fuse" package, please try to install it, not sure how that is done on MacOS.

**Comment by centic9** [comment]
I have added the prerequisites to a new section in the README.

**Comment by zishanjms** [comment]
Thanks !!! You are awesome.
